version: '3.1'

services:
  bot:
    container_name: gucotomap_bot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    # volumes:
    #   - ./gucotomap_files/:/Gucotomap_bot-main/
    #   # - ./gucotomap_files/gucotomap_journal.log:/Gucotomap_bot-main/gucotomap_journal.log
    networks:
      - gucotomap_net

  mongo:
    container_name: gucotomap_db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: supersecretpassword
    ports:
      - 27017:27017
    networks:
      - gucotomap_net

  mongo-express:
    container_name: gucotomap_web
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://admin:supersecretpassword@mongo:27017/
    networks:
      - gucotomap_net

networks:
  gucotomap_net:
    driver: bridge